version: 2
jobs:
  build:
    resource_class: small
    working_directory: ~/narc0tiq/YARM
    parallelism: 1
    shell: /bin/bash --login

    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

    docker:
    - image: cimg/base:current

    steps:
    - checkout
    - run: mkdir -pv $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: sudo apt-get update; sudo apt-get install lua5.2 make zip
    - run: rm Makefile
    - run: wget https://github.com/narc0tiq/factorio-mod-makefile/raw/master/Makefile
    - run: make package clean

    - store_artifacts:
        path: pkg/
